spring.ai.model.chat=openai
spring.ai.model.embedding=openai

spring.ai.openai.base-url=http://localhost:12434/engines/
spring.ai.openai.api-key=_
spring.ai.openai.chat.options.model=ai/gemma4:E2B
spring.ai.openai.embedding.options.model=ai/qwen3-embedding:0.6B-F16
spring.ai.openai.embedding.options.dimensions=768

# PgVector store
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.max-document-batch-size=1024