spring.application.name=talk-to-repo

# Database
spring.jpa.open-in-view=false

# Chat config
spring.ai.model.chat=ollama
spring.ai.model.embedding=ollama

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3-coder:latest
spring.ai.ollama.embedding.options.model=nomic-embed-text-v2-moe:latest
spring.ai.ollama.embedding.options.dimensions=768

# Chat Memory
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# PgVector store
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
