
spring.ai.model.chat=openai
spring.ai.model.embedding=openai

# OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.embedding.options.dimensions=1536

# PgVector store
spring.ai.vectorstore.pgvector.dimensions=1536
