spring.ai.model.chat=openai
spring.ai.model.embedding=openai

spring.ai.openai.base-url=http://localhost:12434/engines/
spring.ai.openai.api-key=_
spring.ai.openai.chat.options.model=ai/gemma4:E2B
spring.ai.openai.embedding.options.model=ai/nomic-embed-text-v2-moe:latest
spring.ai.openai.embedding.options.dimensions=768
